# 将注册信息放在远程上面， 这样可以动态的切换环境
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8761/eureka
           
zuul:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    consumer:
      path: /consumer/**
      serviceId: eureka-client-consumer
    configConsumer:
      path: /configConsumer/**
      serviceId: config-client-consumer
